// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8cpm023tOGq5taXsPfEc-YLI-KDnA9sw',
    appId: '1:567786317416:android:bb73a4afd5f4b15003bddd',
    messagingSenderId: '567786317416',
    projectId: 'hoapital-omor',
    storageBucket: 'hoapital-omor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3NdQvcN6R_AaGhvqUZPos3XTgN4LHig',
    appId: '1:567786317416:ios:f0ca24823813b68703bddd',
    messagingSenderId: '567786317416',
    projectId: 'hoapital-omor',
    storageBucket: 'hoapital-omor.appspot.com',
    androidClientId: '567786317416-hii6e9r9nlvk568hdct3a0ia8eudvaed.apps.googleusercontent.com',
    iosClientId: '567786317416-trv6phrdl6gc272s46iq61a4timh2f3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospital',
  );
}
